device-type/overlay-tablet/frameworks/base/core/res/res/values/config.xml
Move it from project-celadon overlay to tablet overlay.
Jira: OAM-65700
Test: Run the cases in OAM-65700
Signed-off-by: Yan, Walter <walterx.yan@intel.com>
=> Move the round icon config into tablet config.

device-type/overlay-car/frameworks/base/core/res/res/values/config.xml, wlan/overlay-wifi-tethering/frameworks/base/core/res/res/values/config.xml
Jira: None
Test: Enable/Disable Wi-Fi hotspot
Signed-off-by: Babu Chennakesavulu, Raveendra
<raveendra.babu.chennakesavulu@intel.com>
=> Add overlays for Wi-Fi hotspot support

wlan/iwlwifi/wpa_supplicant_overlay_no_tdls.conf
Changes required to comply with Android CDD for Intel WiFi Chipsets.
Tracked-On: OAM-72324
Signed-off-by: Babu Chennakesavulu, Raveendra
<raveendra.babu.chennakesavulu@intel.com>
=> Addinng tdls_auto diabled supplicant config file.

recovery/updater_ab_esp/updater_ab_esp.cpp
Tracked-On: OAM-72792
Signed-off-by: phireg <philippe.regnier@intel.com>
=> ota: remove one trailing space

wlan/iwlwifi/p2p_supplicant_overlay.conf, wlan/iwlwifi/wpa_supplicant_overlay_no_tdls.conf, wlan/wpa_supplicant-common.conf
Remove not applicable configurations blocking p2p causing
VTS failure.
Tracked-On: OAM-75990
Signed-off-by: Amrita Raju <amrita.raju@intel.com>
=> wlan: Changes to make treble compliant

bluetooth/overlay-car/packages/apps/Bluetooth/res/values/config.xml
=> Enable config flag for hfp client connection service

touch/Vendor_1ff7_Product_0f21.idc
Adding the changes to support cvt 4k display
Tracked-On: OAM-88790
Signed-off-by: rbabub <ramesh.babu.b@intel.com>
=> [CIV] Enable 4k Touch device

sdcard/Android.mk, sdcard/fuse.cpp, sdcard/fuse.h, sdcard/sdcard.c, sdcard/sdcard.cpp, vendorsetup.sh
Tracked-On: OAM-88695
Signed-off-by: sgnanase <sundar.gnanasekaran@intel.com>
=> Add vendorsetup.sh with intel path variables

device-type/overlay-tablet/frameworks/base/core/res/res/values/config.xml
Tracked-On: OAM-89767
Signed-off-by: yingzhex yingzhenx.li@intel.com
=> Enable the feature for freeform window managerment on tablet

gpt_bin/gpt_ini2bin.py
Tracked-On: OAM-90212
Signed-off-by: swaroopb <swaroop.balan@intel.com>
=> [CELADON] [CIV][Platform Config] Upgrade Python2 scripts

gpt_bin/gpt_ini2bin.py, recovery/bootloader/releasetools.py, recovery/releasetools.py, recovery/sofia3gr/releasetools.py, recovery/sofia_lte/releasetools.py
Tracked-On: OAM-89920
Signed-off-by: rnaidu <ramya.v.naidu@intel.com>
=> upgrading python 2 to 3

gpt_bin/gpt_ini2bin.py, recovery/bootloader/releasetools.py, recovery/releasetools.py, recovery/sofia3gr/releasetools.py, recovery/sofia_lte/releasetools.py
Tracked-On: OAM-90219
Signed-off-by: rnaidu <ramya.v.naidu@intel.com>
=> Upgrade python 2 to 3

touch/Vendor_056a_Product_489c.idc, touch/Vendor_2386_Product_3115.idc
Tracked-On:
Signed-off-by: Yang, Dong <dong.yang@intel.com>
=> add 2 idc config file for new touch

firmware.mk
=> Add all firmware files including symbolic link files

kernel/lts2019-chromium/kernel-headers/linux/iwl-vendor-cmd.h, kernel/lts2019-chromium/kernel-headers/linux/nl80211.h
=> Add kernel headers for use by vendor HAL libraries

firmware.mk
=> Copy only needed firmwares

wlan/iwlwifi/wpa_supplicant_overlay.conf
=> Enable Wowlan for disconnect trigger

psdapp/filesystem_config/config.fs
=> Remove not used psdapp

rro_overlays/Android.bp, rro_overlays/TetheringOverlay/Android.bp, rro_overlays/TetheringOverlay/AndroidManifest.xml, rro_overlays/TetheringOverlay/res/values/config.xml, rro_overlays/TetheringOverlayGsi/Android.bp, rro_overlays/TetheringOverlayGsi/AndroidManifest.xml, rro_overlays/TetheringOverlayGsi/res/values/config.xml
=> Add rro_overlays for p2p tethering

bluetooth/intel/tablet/bdroid_buildcfg.h
=> Disable WBS as the BT controller does not have support for the feature

kernel/lts2020-yocto/kernel-headers/linux/iwl-vendor-cmd.h, kernel/lts2020-yocto/kernel-headers/linux/nl80211.h
=> Add lts2020-yocto kernel headers

kernel/lts2019-chromium/kernel-headers/linux/iwl-vendor-cmd.h
Tracked-On: OAM-99914
Signed-off-by: Basanagouda Koppad <basanagoudax.n.koppad@intel.com>
=> iwl7000 add vendor command header file

vendorsetup.sh
Tracked-On: OAM-98182
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>
=> Export device intel mixins path

kernel/lts2020-chromium/kernel-headers/linux/iwl-vendor-cmd.h
Tracked-On: OAM-101106
Signed-off-by: Lakshmishree C <lakshmishree.c@intel.com>
=> Update kernel header for iwl7000 driver

kernel/lts2019-chromium/kernel-headers/linux/iwl-vendor-cmd.h, kernel/lts2019-chromium/kernel-headers/linux/nl80211.h
Tracked-On: OAM-102236
Signed-off-by: Lakshmishree C <lakshmishree.c@intel.com>
=> lts2019-chromium: Update kernel headers for use by vendor HAL lib

device-type/overlay-car/frameworks/base/core/res/res/values/config.xml
Tracked-On: OAM-102506
Signed-off-by: Chen Luhai <luhai.chen@intel.com>
=> Disabe gnss based time source

kernel/lts2021-chromium/kernel-headers/linux/iwl-vendor-cmd.h, kernel/lts2021-chromium/kernel-headers/linux/nl80211.h
Tracked-On: OAM-103397
Signed-off-by: Lakshmishree C <lakshmishree.c@intel.com>
=> Kernel: Headers added for Chromium kernel v5.15.44

power_profile/LICENSE
Add license file for vendor-intel-common power profile
Tracked-On: OAM-104681
Signed-off-by: Shwetha B <shwetha.b@intel.com>
=> License for power profile

overlays_hdmisettings/LICENSE
Changes include:
- Adding Apache license file
Tracked-On: OAM-104825
Signed-off-by: Lu Yang A <yang.a.lu@intel.com>
=> add license file for overlays_hdmisettings

bluetooth/intel/LICENSE, rro_overlays/LICENSE, wlan/LICENSE
Add LICENSE file with required license info for Bluetooth and WiFi.
Signed-off-by: Bharat B Panda <bharat.b.panda@intel.com>
=> Update license inforamtion for connectivity

kernel/linux-intel-lts2021/kernel-headers/linux/iwl-vendor-cmd.h, kernel/linux-intel-lts2021/kernel-headers/linux/nl80211.h
=> Add linux-intel-lts2021 headers for use by vendor HAL libraries

kernel/lts2019-chromium/kernel-headers/linux/iwl-vendor-cmd.h
Tracked-On: OAM-105153
Signed-off-by: rajucm <raju.mallikarjun.chegaraddi@intel.com>
=> kernel: update iwl kernel-headers for vendor-hal usage

host_scripts/guest_time_keeping.sh, host_scripts/setup_cam_sharing.sh, host_scripts/setup_host.sh, host_scripts/start_flash_usb.sh
=> Moving host scripts to device/intel/common project

allow3rdpartyapponinternal/overlay/frameworks/base/core/res/res/values/config.xml, aosp_carrier-config/init.aosp-config.rc, aosp_carrier-config/prop/ATT.prop, aosp_carrier-config/prop/CMCC.prop, aosp_carrier-config/prop/NTT.prop, aosp_carrier-config/prop/VZW.prop, framework/android.software.cant_save_state.xml, tools/LICENSE, ufo/LICENSE
Also deleting the non required module aosp_carrier_config as we don't support telephony stack as of now.
Tracked-On: OAM-104628
=> Adding LICENSE files to the required modules

thermal/thermal-daemon/LICENSE, touch/LICENSE, usb-gadget/LICENSE
Adding license file to required module
thermal/thermal-daemon
touch
usb-gadget
Tracked-On: OAM-108600
=> LICENSE for thermal,usb-gadget and touch

host_scripts/ai_raw_tensor.sh, host_scripts/setup_ai_dispatcher.sh
download and install intel compute runtime packages required for GPU inference
to setup inference via GPU, run sudo -E scripts/setup_host.sh -i GPU
Tracked-On: OAM-108702
=> Enable GPU device for remote infer

thermal/thermal-daemon/thermal-conf.xml
Modified xml file to add configuration for ADL
IVI RVP i7-12700H and i5-12500H platform.
Tracked-On: OAM-109803
=> Thermal Daemon configuration for IVI Platform

rro_overlays/NetworkOverlay/Android.bp, rro_overlays/NetworkOverlay/AndroidManifest.xml, rro_overlays/NetworkOverlay/res/values/config.xml
=> Configure rro overlay for overriding captive_portal_http_url

graphics/mali-vp/egl.cfg, graphics/mali/egl.cfg
=> Remove the unused graphic component

host_scripts/setup_host.sh
1. Fix the reset issue
2. Got updates
Tracked-On: OAM-110647
=> Upgrade QEMU to version 7.2.3

thermal/thermal-daemon/LICENSE, touch/LICENSE, usb-gadget/LICENSE
LICENSE for thermal,usb-gadget and touch
adding Apache License Version 2.0
http://www.apache.org/licenses/
=> Lincense usb thermal touch

kernel/lts2020-chromium/kernel-headers/linux/iwl-vendor-cmd.h, kernel/lts2020-chromium/kernel-headers/linux/nl80211.h
Update kernel header for iwl7000 & nl80211
Tracked-On: OAM-111019
=> Update kernel header for iwl7000 & nl80211

kernel/lts2020-chromium/kernel-headers/linux/iwl-vendor-cmd.h, kernel/lts2020-chromium/kernel-headers/linux/nl80211.h
Update iwl7000 & nl80211 kernel headers for kernel 
version 5.10.178
Tracked-On: OAM-111233
=> Update kernel-headers for the kernel-5.10.178

bluetooth/intel/LICENSE, rfkill/LICENSE, wlan/iwlwifi/LICENSE
License file was missing for Intel wlan iwlwifi.
Added LICENSE file for iwlwifi
Tracked-On: OAM-111376
=> Add LICENSE file for Intel iwlwifi module

sensors/LICENSE
adding Apache License Version 2.0
http://www.apache.org/licenses/
Tracked-On: OAM-111389
=> Add LICENSE for sensors

thermal/thermal-daemon/thermal-conf.xml
Modified xml file to add configuration for pre A Sample RPL i5-1350PRE platform.
Tracked-On: OAM-111206
=> Thermal Daemon configuration for RPL i5-1350PRE

thermal/thermal-daemon/thermal-conf.xml
Finetuned thermal trip parameters and rapl limit to improve performance.
=> Thermal fine tuning for RPL i5-1350PRE

thermal/thermal-daemon/thermal-conf.xml, thermal/thermal-daemon/thermal-cpu-cdev-order.xml
=> configuring fan cooling device in thermal-daemon for IVI

thermal/thermal-daemon/thermal-conf.xml, thermal/thermal-daemon/thermal-cpu-cdev-order.xml
This reverts commit e0ef534ec5c1036a96dc1cd347a696170fdf09ad.
=> Revert "configuring fan cooling device in thermal-daemon for IVI"

thermal/thermal-daemon/thermal-conf.xml
Add thermald config for apollo.
Tracked-On: OAM-115355
=> Add thermald config for apollo

gpt_bin/gpt_ini2bin.py
This reverts commit 1d3475c6ab4db0f8d22b7710e1fd1fe2c7486ae1.
Reverting since boot issue was seen on MBL Fab-B board.
=> Revert "Migrate gpt_ini2bin.py to python3"

thermal/thermal-daemon/thermal-conf.xml
Modified xml file to add configuration for MTL NUC platform.
Tracked-On: OAM-122349
=> Thermal Daemon configuration for MTL NUC Platform

gpt_bin/gpt_ini2bin.py
Test Done: Boot check on civ and base_aaos
Tracked-On: OAM-124331
=> Migrate gpt_ini2bin.py to python3

rro_overlays/WifiOverlay/Android.bp, rro_overlays/WifiOverlay/AndroidManifest.xml, rro_overlays/WifiOverlay/OWNERS, rro_overlays/WifiOverlay/res/values/config.xml
For wificond to broadcast wifi region we need this config to be enabled.
Test done:
1. Flash the image with changes
2. Connect to wifi Network
3. Ran Cts Test cases in both IN/CN location
4. 5GHz ap working and TC also passing
Tracked-On: OAM-124530
=> Creating overlay for Config Nl80211RegChangedEvent

firmware.mk
=> dkms: optimize the dg2 kernel driver loading time

kernel/lts2021-chromium/kernel-headers/linux/iwl-vendor-cmd.h
=> Update kernel header for v5.15.167 rebase

thermal/thermal-daemon/thermal-conf.xml
Calibrate thermal trip points for MTL platform.
Updated fine tuned temperature trip points and rapl power limits for
Meteorlake platform.
Test Done -
Platform : MTL NUC
Tracked-On: OAM-125941
Signed-off-by: Rajani Ranjan <rajani.ranjan@intel.com>
=> Calibrate thermal trip points for MTL platform.

touch/Vendor_04f3_Product_4253.idc
add idc config file for new touch
Vendor_04f3_Product_4253.idc:
ELAN Touch
Tracked-On: OAM-128153
Signed-off-by: Rajani Ranjan <rajani.ranjan@intel.com>
=> add idc config file for new touch

filesystem_config/config.fs
=> Define a new uid for gnss hal

rdtsc/rdtsc.c
=> Fix coverity issues

device-type/overlay-car/frameworks/base/core/res/res/values/config.xml, device-type/overlay-tablet/frameworks/base/core/res/res/values/config.xml
Tests done:
- Android boot to UI
- adb reboot
Tracked-On: OAM-129809
=> Update default refresh rates to boot with eDP panels
