projectceladon/device-intel-common

bluetooth/intel/car/bdroid_buildcfg.h
bluetooth/intel/tablet/bdroid_buildcfg.h

Description:
- To make IVI work as Audio Sink device, need to enable
flag "BTA_AV_SINK_INCLUDED" in system/bt.
- Since this flag should be enabled only for IVI,
created seperate header file for both IVI and tablet.
Jira: https://jira01.devtools.intel.com/browse/OAM-65576
Test:
- BT AVRCP should work, user shouble be able to control music
from Bluetooth Audio App on kabylake IVI - PASS
Signed-off-by: Umesh Agarwal <umeshx.agarwal@intel.com>

Introduced "bdroid_buildcfg.h" based on device type   to enable BTA_AV_SINK_INCLUDED for IVI only

---

bluetooth/intel/car/bdroid_buildcfg.h

issue :
- Pixel phone getting disconnected, after MAP operations are performed
fix:
- As the sniff sub-rating is optional, disable it.
Jira: https://jira01.devtools.intel.com/browse/OAM-65440
Test: 
1) connect Pixel phone
2) Perform MAP operations
Expected behavior  -> Pixel phone should stay connected
Actual Behavior -> Pixel phone is connected.
Signed-off-by: anitha3x <anithax.h.chandrasekar@intel.com>

Disable sniff sub-rating causing timeout issue During SST testing

---

bluetooth/overlay-tablet/packages/apps/Bluetooth/res/values/config.xml

Description:
- Addition of configuration files 'overlay-tablet' to
enable all the profiles relevant to TABLET, except A2DP
and AVRCP.
- Disabled A2DP, AVRCP, since we do not support
New AVRCP for Android P
Tracked-On: OAM-67866
Signed-off-by: anitha3x <anithax.h.chandrasekar@intel.com>

Added configuration files for celadon TABLET

---

bluetooth/overlay-car/packages/apps/Bluetooth/res/values/config.xml

Description:
At the time of reboot, reference phone didn't
reconnect automatically.To overcome this issue
we have set hfp_client TRUE,so that at the time
of auto-connect,Car service will intiate connect
for bt profiles
Tracked-On: OAM-70153
Signed-off-by: umeshagx <umeshx.agarwal@intel.com>

Enable support for HID  devices in overlay-car packages

---

recovery/releasetools.py

Test: build image without slot-ab and avb
Tracked-On: OAM-71458
Signed-off-by: phireg <philippe.regnier@intel.com>

boot: fix UnzipTemp API call

---

framework/android.software.cant_save_state.xml

CTS failure due to don't support feature: FEATURE_CANT_SAVE_STATE
the feature is for supporting the R.attr.cantSaveState API( sdk28),
the cantSaveState declare that this application can't participate
in the normal state save/restore mechanism.
Test: run cts -m CtsAppTestCases
-t android.app.cts.ActivityManagerProcessStateTest#testCantSaveStateLaunchAndBackground
run cts -m CtsAppTestCases
-t android.app.cts.ActivityManagerProcessStateTest#testCantSaveStateLaunchAndSwitch
Tracked-On: OAM-71298
Signed-off-by: Wang, ArvinX <arvinx.wang@intel.com>

Fix cts failure in CtsAppTestCases

---

recovery/updater_ab_esp/updater_ab_esp.cpp
set_storage/set_storage.c

1): Initialized 'file_path' array when used in this function.
2): Fix overflow buffer and unvalidated string dereference.
3): Fix object 'path' was used after being freed by calling 'free'.
Change-Id: Id817468f43fd3d7a1eb820b27bd66390b8ea89c2
Tracked-On: OAM-72792
Signed-off-by: sunxunou <xunoux.sun@intel.com>
Signed-off-by: phireg <philippe.regnier@intel.com>

[PORT FROM OMR1] Clean critical KW issue in BOOT-OTA domain

---

set_storage/Android.mk

After enable treble/first stage mount support, need put the set_storage
to vendor/bin/
Tracked-on: OAM-71435
Signed-off-by: Ming Tan <ming.tan@intel.com>

set_storage: enable first stage mount support.

---

device-type/overlay-car/frameworks/base/core/res/res/values/config.xml

After the FEATURE_APP_WIDGETS is disable, it will cause some applications
crashed when use the AppWidget. Such as play music, calendar, email.
Change-Id: I12ac972bb87c583ef508442ae0b17f2e3db59a7b
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-75541
Signed-off-by: Lei,RayX <rayx.lei@intel.com>
Signed-off-by: Wang, ArvinX <arvinx.wang@intel.com>

Enable AppWidgetService even the feature is disable

---

bluetooth/overlay-tablet/packages/apps/Bluetooth/res/values/config.xml

A2DP and AVRCP profile are disabled resulting in bluetooth
app crash.
As A2DP and AVRCP profile is supported, enable the profiles.
Tracked-On: OAM-75947

bluetooth: Fix for bluetooth app crash

---

audio/overlay-car-legacy/frameworks/base/core/res/res/values/config.xml

Enable input events for HDMI plug/unplug
Enable input events for HDMI plug/unplug
Tracked-On: OAM-84728
Signed-off-by: M, Kumar K <kumar.k.m@intel.com>

Enable input events for HDMI plug/unplug

---

audio/overlay-car-legacy/frameworks/base/core/res/res/values/config.xml

71e75cd overlay config_useFixedVolume for fix audio issue, but it
copy some others config too that were used by others features, it
will cause some bug in different product.
Remove these duplicated overlay configs to fix no split screen feature
issue in Tablet device.
Tracked-On: OAM-86816

Fix no split screen feature issue in Tablet

---

audio/policy-configuration/Android.mk

Fix build warnings reported in OAM-86853 - due to duplicate
audio-policy-configuration xml files. Add conditional
compile flags for policy config files.
Tracked-On:  https://jira01.devtools.intel.com/browse/OAM-86853
Signed-off-by: Aravind Siddappaji <aravindx.siddappaji@intel.com>

[Celadon Q] Fix build warnings in OAM-86853

---

wlan/overlay-disable_keepalive_offload/frameworks/base/core/res/res/values/config.xml

Keepalive packet offloading is enabled by default. CTS test cases
are failing as the keepalive offloading event is not received.
As keepalive offloading is not supported, override the configs
to disable it to address CTS failures.
Tracked-On: OAM-86930

Disable keepalive offload to address CTS issue

---

bluetooth/car/bdroid_buildcfg.h
bluetooth/overlay-car/frameworks/base/core/res/res/values/config.xml
bluetooth/overlay-tablet/frameworks/base/packages/SettingsProvider/res/values/defaults.xml
bluetooth/overlay-tablet/packages/apps/Bluetooth/res/values/config.xml
bluetooth/tablet/bdroid_buildcfg.h
wlan/p2p_supplicant_overlay.conf
wlan/wlan.conf
wlan/wpa_supplicant_overlay.conf

Changes done:
- Add overlays and configuration files needed for
supporting multiple connectivity modules.
- Marvell 8897(bluetooth over usb) and Intel Connectivity modules
are verified with this patch.
Tracked-On: OAM-88286

Bluetooth and WLAN mixin changes to adopt aaf

---

action-authorization/Android.mk

rma tools should use crypto library of build machine.
Tracked-On: OAM-90438
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

rma: change crypto library

---

bluetooth/car/bdroid_buildcfg.h
bluetooth/overlay-car/frameworks/base/core/res/res/values/config.xml

This change makes Bluetooth work on NUC8i5BEH2 devices (among others) configured with `device-type: car`.
As a bonus, I noticed bluedroid's default name doesn't get expanded by mixin, so I just replaced it with a normal name.

Bluetooth fix on `device-type: car` builds

---

bluetooth/tablet/bdroid_buildcfg.h

Bluetooth device name is shown as {{target}} in UI.
Fix the issue by setting bluetooth device name properly instead
of {{target}}.
Tracked-On: OAM-94329

Set bluetooth device name

---

wlan/iwlwifi/wpa_supplicant_overlay.conf

As supplicant rc entry from external/wpa_supplicant_8 is going
to be used, instead of providing param as parameter to service
start, use_p2p_group_interface is set in wpa_supplicant conf file.
Tracked-On: OAM-95969

Set driver param use_p2p_group_interface=1

---

thermal/thermal-daemon/thermal-conf.xml

Thermal Fine tuning for TGL NUC BM.
Finetuned thermal trip parameters to avoid unexpected 
shutdown for TGL BM Device.
Tracked-On: OAM-99878
Signed-off-by: vilasrk <vilas.r.k@intel.com>

Thermal Fine tuning for TGL NUC BM

---

rro_overlays/TetheringOverlay/AndroidManifest.xml

Changes made to update the correct tethering package name
that started used in Android S onwards,
"com.android.networkstack.tethering"
Traked-On: OAM-102707
Signed-off-by: Bharat B Panda <bharat.b.panda@intel.com>

Update Tethering package name in rro_overlays

---

rro_overlays/ServiceConnectivityResourcesOverlay/Android.bp
rro_overlays/ServiceConnectivityResourcesOverlay/AndroidManifest.xml
rro_overlays/ServiceConnectivityResourcesOverlay/res/values/config.xml

Keepalive packet offloading is enabled by default. CTS test cases
are failing as the keepalive offloading event is not received.
As Keepalive is not supported, configure the rro overlay for
ServiceConnectivityResource to disable the
networkSupportedKeepaliveCount to fix the Cts Net TC module issue.
Tracked-On: OAM-104109
Signed-off-by: gollarx <ratnakumarix.golla@intel.com>

Configure rro overlay for connectivity to address CTS issue

---

graphics/mali-vp/egl.cfg
graphics/mali/egl.cfg

The mali folders are no longer used anymore, clean up them and keep the graphics folder for future possible use.
Tracked-On: OAM-104671
Signed-off-by: Lu Yang A <yang.a.lu@intel.com>

Clean up the mali folders in graphics

---

media/wrs_omxil_components.list

Only OMX lib is included in the media folder.
OMX is not used any more
Signed-off-by: Shaofeng Tang <shaofeng.tang@intel.com>

Clean up media

---

firmware.mk

Creation of boot.img fails due to size exceeding maximum size limit of 40MB.
When all guc and huc files are included, boot.img size is exceeding the max size of 40MB.
Copy GuC and HuC files of supported platforms to avoid boot image size exceeding set maximum size limit.
Change-Id: Ice350188cb7acad12f1c0edcf05e59c3c53c6db6
Tracked-On: OAM-104960
Signed-off-by: Sundar Gnanasekaran <sundar.gnanasekaran@intel.com>

Fix boot.img creation failue due to size limit

---

host_scripts/ai_raw_tensor.sh
host_scripts/setup_ai_dispatcher.sh
host_scripts/setup_host.sh

add remote inference in civ host as a service.
Adds scripts to setup and start raw tensor service on host.
To setup ai-dispatcher, while doing host setup use "sudo -E ./scripts/setup_host.sh -i"
Tracked-On: OAM-104143

Enable ai-dispatcher raw tensor service with vsock

---

media/wrs_omxil_components.list

OMX is not used on celadon anylonger.
Tracked-On: OAM-110735

Remove the unnecessary component list

---

host_scripts/setup_host.sh

Changes include:
- Move the firmware update of graphics and wifi inside ubu_update_fw to avoid duplication in multiple functions.
- Update firmware tag to 20230625
- Remove not used wifi firmware update function.
Tracked-On: OAM-111145

Do firmware update of graphics and wifi inside ubu_update_fw

---

kernel/lts2019-chromium/kernel-headers/linux/iwl-vendor-cmd.h

Rebasing kernel headers for kernel version v5.4.259.
Tracked-On: OAM-113179

kernel_5.4.259: update kernel headers for vendor lib usage

---

bluetooth/overlay-car/packages/apps/Bluetooth/res/values/config.xml

Enable HID host profile for Bluetooth car use cases, which enables the Bluetooth HID joystick, mouse, keyboard connection for ivi.
Validated the BT Sony joystick connection and its able to control the ivi UI.
Tracked-On: OAM-112821
Signed-off-by: Gowtham Anandha Babu <gowtham.anandha.babu@intel.com>

Fix Bluetooth joystick connection issue

---

kernel/linux-intel-lts2022/kernel-headers/linux/iwl-vendor-cmd.h
kernel/linux-intel-lts2022/kernel-headers/linux/nl80211.h

Changes include:
- Added kernel headers for use by vendor HAL libraries
Tracked-On: OAM-113581

Add 6.1 sriov supported kernel headers for use by vendor HAL libraries

---

host_scripts/setup_host.sh

As kernel panic is  seen on SRIOV boot, rolling back firmware package to version linux-firmware-20230919 until the latest kernel and firmware combo is verified successfully.
Tests done:
- setup_host runs and firmwares are updated properly on host side.
- Graphics, Wi-Fi and bluetooth firmwares are getting loaded properly on host side.
Tracked-On: OAM-114193

Fix kernel panic when booted in SRIOV config

---

host_scripts/setup_host.sh

With latest kernels, android is not booting in SR-IOV config.
With latest kernel, GuC submission and HuC authentication is determined by the driver itself. So, enable_guc module parameter should not be overrided. Also, max_vfs parameter needs to be set for spawning upto max_vfs number of virtual functions.
Update the kernel command line parameter for Android to boot with SR-IOV config.
Tests done:
- Android boot
- adb reboot
Tracked-On: OAM-114191

Update kernel command line parameters for sriov

---

host_scripts/setup_host.sh

Update firmware to latest tag 20240220 as part of kernel rebase.
Tests done:
- Ubuntu boot
- Wi-Fi and Bluetooth functionality on ubuntu
- i915 firmware load on ubuntu
Tracked-On: OAM-116655

Update firmware to tag 20240220

---

host_scripts/setup_host.sh

The commit id for BT firmware files are old and does not contain the fw files for AX211 MA sample.
Upgrade the BT firmware to latest commit id, which includes ibt-0180-0041 fw files. And push the same to host so that setup host will succeed.
Tests done:
1. Run setup host script
2. Reboot host
3. Check host BT is up
4. Flash binary and boot CiV14 with GVT-d
5. Boot check CiV14
6. Verify CiV14 BT on/off
Tracked-On: OAM-117261

Update BT FW for AX211 MA sample

---

rro_overlays/NetworkOverlay/Android.bp
rro_overlays/NetworkOverlay/AndroidManifest.xml
rro_overlays/NetworkOverlay/res/values/config.xml

Use "https://connect.rom.miui.com/generate_204" as portal https url to replace default url "https://www.google.com/generate_204"
Test: Connect wifi and check network status.
Tracked-On: OAM-118021

Configure rro overlay for overriding captive_portal_http_url

---

rro_overlays/CarServiceOverlay/Android.bp
rro_overlays/CarServiceOverlay/AndroidManifest.xml
rro_overlays/CarServiceOverlay/res/values/config.xml
rro_overlays/CarServiceOverlay/res/xml/overlays.xml

Add CarServiceOverlay rro
Test: Flash GSI image, and dumpsys car_service --services CarOccupantZoneService
Tracked-On: OAM-121009
Signed-off-by: Hongcheng Xie <hongcheng.xie@intel.com> 
Signed-off-by: Cheng, Ninghuix <ninghuix.chen@intel.com>

Configure rro overlay for overriding config_occupant_display_mapping

---

wlan/iwlwifi/p2p_supplicant_overlay.conf

Currently wifi p2p group shares network interface with primary interface used by normal STA wifi function since p2p_no_group_iface is set to 1. When wpa_supplicant set P2P mode on primary interface, it will first shut down the interface then set P2P mode and turn it up at last. wifip2pservice would capture the shut down event and stop p2p setup, then the concurrency test will be failed.
Now set p2p_no_group_iface to 0 and then p2p group will use a different network interface compared to primary interface used by normal STA wifi function, so that wpa_supplicant will not do shutdown-up operation.
Tracked-On: OAM-119784

fix wifip2p concurrencyTest failure in CTS test

---

device-type/overlay-car/frameworks/base/core/res/res/values/config.xml

Car-messenger app is not syncing the sms/mms
from BT connected reference phone. Making
default messaging application as car-messenger
in overlay-car config helps to sync the
sms/mms successfully
Test: MessageAccessProfile
1. Connect bluetooth with any mobile device.
2. Give all the permissions for all that are required.
3. Check messages are able to sync in message application.
Tracked-On: OAM-119719

Adding SMS application to default

---

firmware.mk

Latest build_image script used to build vendor.img expects the file paths in the format folder_path/file_name whereasiwlwifi firmware copy script provides the path firmware/./iwlwifi* resulting in build_image failing with firmware/./iwlwifi-100-5.ucode: not normalized.
Modified the find option to fix the path issue.
Tests done:
- Android boot with GVT-d and BM
- Wi-Fi on/off/scan/connect/disconnect
- adb reboot
Tracked-0n: OAM-123050

Fix vendor.img creation failing with latest build_image script

---

device-type/overlay-car/frameworks/base/core/res/res/values/config.xml

when a BT HFP call comming,
There is no UI for answering the incoming calls on the IVI device. This patch can fix this issue,
Tests:
it can reject BT HFP call now.
Tracked-On: OAM-123273

Fix BT HFP call can not reject call issue

---

bluetooth/overlay-car/packages/modules/Bluetooth/android/app/res/values/config.xml

By default five audio a2dp devices can be connected in AOSP bt-stack, but we support only a2dp streaming at a time. This is causing ambiguity when connect 2nd pixel, the media profile is enabled for both 1st and 2nd pixel, causing ambiguity among user.
Set the maximum connected audio a2dp device as one, which resolves the ambiguity and when connect 2nd pixel device.
Tests-done:
1. Flash BM
2. Connect Pixel1
3. Pixel1 media profile should be connected
4. Connect Pixel2
5. Pixel2 media profile should not be connected, it should be in disconnected state
Tracked-On: OAM-123265

Make max connected audio a2dp device as one

---

device-type/overlay-car/frameworks/base/core/res/res/values/config.xml
device-type/overlay-car/frameworks/base/core/res/res/xml/config_user_types.xml

From second reboot onwards, home and all apps buttons are getiing disabled. If screen lock is set then this issue is not observed. Reason- Screen lock condition was getting true even there was no screen lock.
Setting default disabled screen lock value to true. Also enabling sms & call feature for secondary users.
Tests: Reboot device few times and check. All navigation keys are working.
Tracked-On: OAM-124177

Fixed for Home/ALL_APPS button in AAOS.

---

wlan/overlay-disable_keepalive_offload/frameworks/base/core/res/res/values/config.xml

Keep alive feature is disabled to resolve below CTS issue in 2019. That time our controller was not supporting this feature.
https://jira.devtools.intel.com/browse/OAM-86930
Now we support keep alive, CTS is expecting keep alive slots. After setting config_reservedPrivilegedKeepaliveSlots, config_allowedUnprivilegedKeepalivePerUid values to 2 Following Cts is passing:
android.net.cts.ConnectivityManagerTest#testSocketKeepaliveUnprivileged
Tests done:
1. Flash BM
2. run cts -m CtsNetTestCases -t android.net.cts.ConnectivityManagerTest
3. All test should pass
Tracked-On: OAM-119906

Configure KeepAlive for CTS

---

device-type/.gitignore
device-type/README

This patch will add all files and folders inside device-type folder. This will ignore showing the embargoed projects.
Tests Done: git status
Tracked-On: OAM-126628

Add .gitignore file for device-type

---

rdtsc/Android.mk
rdtsc/rdtsc.c

rdtsc is used to read tsc to measure cold boot time.
Test done: Cold boot
Tracked-On: OAM-129753

Add rdtsc source code

---

wlan/overlay-disable_keepalive_offload/frameworks/base/core/res/res/values/config.xml

The KeepAlive feature was disabled in OAM-86930.
Now the this feature is supported, mentioned in below jira OAM-119906
After setting below configuration values to 2, enables the feature
- config_reservedPrivilegedKeepaliveSlots
- config_allowedUnprivilegedKeepalivePerUid
Tests done:
- Android boot-up success
- All testcase are passing run cts -m CtsNetTestCases -t android.net.cts.ConnectivityManagerTest
Tracked-On: OAM-127805

Enable KeepAlive feature to address CTS issue
